version: "3.7"
services:
    reverse-proxy:
        restart: always
        build: .
        container_name: reverse-proxy
        environment:
            COUNTRY_NAME_2LETTER_CODE: ${COUNTRY_NAME_2LETTER_CODE}
            STATE_NAME: ${STATE_NAME}
            CITY_NAME: ${CITY_NAME}
            SERVER_NAME: ${SERVER_NAME}
            EMAIL: ${EMAIL}
            ORGANIZATION_NAME: ${ORGANIZATION_NAME}
            ORGANIZATION_UNIT_NAME: ${ORGANIZATION_UNIT_NAME}
            AUTH_PASSWORD: ${AUTH_PASSWORD}
            AUTH_USERNAME: ${AUTH_USERNAME}
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./html:/usr/share/nginx/html
        ports:
            - 443:443
